### ISSUE TITLE
can't easily edit the codeblocks in live preview

### ISSUE THREAD

**Issue by KraXen72** [mProjectsCode/obsidian-shiki-plugin#1]
-   [x] The Plugin is up to date
-   [x] Obsidian is up to date

**Describe the bug**
In live preview, there is only a copy button, covering the edit button.
 clicking on the codeblock does not turn it into an editable thing.

**To Reproduce**
add a codeblock, turn on the plugin, go to Live Preview

**Expected behavior**
clicking on the codeblock should go into edit more.
Or, move the copy code button elsewhere, so it doesen't obscure the edit button.

**Screenshots**
-

**Occurs on**

-   [x] Windows
-   [ ] macOS
-   [ ] Linux
-   [ ] Android
-   [ ] iOS

**Plugin version**
0.2.1

**Additional context**
-

**Comment by mProjectsCode** [comment]
> clicking on the codeblock does not turn it into an editable thing.

That is by design, allowing you to freely select text in the code block.

> In live preview, there is only a copy button, covering the edit button.

I will try to move the copy button.

**Comment by mProjectsCode** [comment]
I moved the copy button to the lower right corner
