### ISSUE TITLE
Is there a way to highlight inline code too?

### ISSUE THREAD

**Issue by nuanjanP** [mProjectsCode/obsidian-shiki-plugin#10]
**Is your feature request related to a problem? Please describe.**
I'm looking for a way to specify a language for inline code (in markdown syntax) so that it is highlighted.

I've tried inline raw HTML such as `<code class="language-python">print('hello world')</code>`. This does get highlighted, but also automatically turned into a code block. I'd like it to remain as inline code.

**Describe the solution you'd like**
It would be great if there's a way we can specify language for inline code in markdown syntax (that is, code using just backticks, not raw HTML) and highlight it accordingly.

**Comment by mProjectsCode** [comment]
Markdown does not support specifying a language for inline code blocks.

**Comment by nuanjanP** [comment]
I apologize for my previously ill-defined question. What I'm meaning to ask is that, is there a non-standard syntax that can be used so that this plugin also targets a particular instance of inline code?

The reason I'm asking is because there are Obsidian plugins that use non-standard syntax to specify a language for inline code and then highlight it accordingly. For example,

- [Inline Code Highlight](https://github.com/Dimava/inline-code-highlight) uses `` `'<LANGUAGE> ...` `` (as in, `` `'python print('Hello World!')` ``)
- [Code Styler](https://github.com/mayurankv/Obsidian-Code-Styler) uses `` `{<LANGUAGE>} ...` `` (as in, `` `{python} print('Hellow World!')` ``)

Thank you in advance for your answer.
