### ISSUE TITLE
conflict with `Typst Renderer` plugin

### ISSUE THREAD

**Issue by CatCodeMe** [mProjectsCode/obsidian-shiki-plugin#2]
**Describe the bug**
I use `Typst Renderer` plugin to render typst code . I find that's confict with `obsidian-shiki-plugin`

**To Reproduce**

1. test code
```md

```typst
#import "@preview/badgery:0.1.1": *

#menu("Menu", "Sub-menu", "Sub-sub menu", "Action")
\```

```
- remove the \ in the end when copy demo code.

**Expected behavior**

1. I hope this plugin could support more config , like  `exclude`  to ignore these code-block like `typst` or another 'language'  like `mermaid `?
2. another question, I hope to support more config , like  custom theme 

**Screenshots**
<img width="1440" alt="image" src="https://github.com/mProjectsCode/obsidian-shiki-plugin/assets/11496772/628719ab-c194-4f80-b4ef-fdbbe93f3b46">

**Occurs on**

-   [ ] Windows
-   [X] macOS
-   [ ] Linux
-   [ ] Android
-   [ ] iOS

**Plugin version**
latest version

**Additional context**

**Comment by mProjectsCode** [comment]
1. I can add some exclude options
2. the colors/theme is dependent on your obsidian theme. You can also override colors with a CSS snippet.

**Comment by CatCodeMe** [comment]
> 1. I can add some exclude options
> 2. the colors/theme is dependent on your obsidian theme. You can also override colors with a CSS snippet.

thanks for your awesome work. Theme option is that I found there are some predefine themes, like github-light,   in expressive code site. But use css-snippet also works.

**Comment by mProjectsCode** [comment]
Yes, EC allows for different themes, but I wrote some custom logic that makes it take the colors of your Obsidian theme.

**Comment by mProjectsCode** [comment]
I just added settings to disable the plugin for certain languages.
