### ISSUE TITLE
Shell script shows three big grey dots

### ISSUE THREAD

**Issue by niwazukihon** [mProjectsCode/obsidian-shiki-plugin#20]
-   [x] The Plugin is up to date
-   [x] Obsidian is up to date

**Describe the bug**
I found that for codeblocks with `bash` and `powershell` as language, the plugin will show three big grey dots at the top of the codeblocks.

**To Reproduce**

1. Create a codeblock with language `bash` or `powershell`.
2. Error.

**Expected behavior**
No big dots.

**Screenshots**
<img src="https://github.com/user-attachments/assets/29e425c6-7fd7-4ba5-8ce4-b4b2abffd4f1" width=60%/>
<img src="https://github.com/user-attachments/assets/a8392647-ad23-4351-a585-fa6d21d0adfe" width=60%/>

**Occurs on**
-   [x] Windows
-   [ ] macOS
-   [ ] Linux
-   [ ] Android
-   [ ] iOS

**Plugin version**
0.4.1

**Additional context**

I also hope that the language of a codeblock is shown on the top right of the codeblock, like the default behavior. Currently after enabling the plugin I can no longer tell the language without going into the codeblock.

**Comment by mProjectsCode** [comment]
That is an intentional feature of expressive code, see https://expressive-code.com/key-features/frames/#terminal-frames

**Comment by niwazukihon** [comment]
I see.. This behavior can be disabled by setting `frame="none"`. It would be great to be able to set those options for languages globally in the plugin settings. For now I'll just disable the plugin for bash and powershell.
