### ISSUE TITLE
[Feature Request] Import custom languages

### ISSUE THREAD

**Issue by acrylicus** [mProjectsCode/obsidian-shiki-plugin#21]
**Describe the solution you'd like**
I work in Networking and I love that N++ has options for syntax highlighting for certain configurations. I am happy to put the legwork into converting a N++ syntax highlighting library to whatever format is required here, but I can't seem to find a way to do it in the current release.

**Additional context**
To give you an idea, there are loads of "User Defined Languages" that you can install on Notepad++ found here
https://github.com/notepad-plus-plus/userDefinedLanguages/blob/master/UDLs/Fortinet_FortiOS_FGT_by_DPBarbosa.xml

**Comment by LaurentOngaro** [comment]
same for me. 
I've tried to understand to code and the doc to add a custom langage but the code was too obscur for me and I did not managed.
It could be very cool to have the possibility to add some langages

**Comment by mProjectsCode** [comment]
just added this in 11746b0

**Comment by mProjectsCode** [comment]
released in https://github.com/mProjectsCode/obsidian-shiki-plugin/releases/tag/0.4.2-canary.20240915T115847

**Comment by acrylicus** [comment]
Works perfectly!!! Thank you!!

<img width="531" alt="image" src="https://github.com/user-attachments/assets/537dbd25-320b-42fb-b3ca-290e6c65cc0b">
