### ISSUE TITLE
Not compatible with Excalidraw Plugin from latest version

### ISSUE THREAD

**Issue by S4njer** [mProjectsCode/obsidian-shiki-plugin#22]
**Is your feature request related to a problem? Please describe.**
Yes, I can't use Shiki Highlighter because i can't use Excalidraw, it occurs with a conflict in the codeblock name of the Excalidraw Data, whose codeblock name is "compressed-json".

**Describe the solution you'd like**
I'd like to get compatibility between the plugins, because I use both.

**Additional context**
I suppose that the Shiki Highlighter is blocking the codeblock to be read from Excalidraw.

**Comment by mProjectsCode** [comment]
You can disable specific code blocks in the plugin settings.

**Comment by acrylicus** [comment]
Hi @mProjectsCode this doesn't seem to fix things - I have tried disabling loads of languages 
<img width="874" alt="image" src="https://github.com/user-attachments/assets/0499ecf1-8255-4395-8333-404199903994">

But unfortunately Excalidraw still does not render when your plugin is enabled

<img width="842" alt="image" src="https://github.com/user-attachments/assets/58d05d08-208d-4381-bbae-fa77ac23e1bf">

**Comment by mProjectsCode** [comment]
Can you provide me with an entire note so that I can try to debug this? I am not familiar with the Excalidraw plugin.

**Comment by acrylicus** [comment]
Sure!

Here is an example of an excalidraw file in markdown

----------EXCALIDRAW

==⚠  Switch to EXCALIDRAW VIEW in the MORE OPTIONS menu of this document. ⚠== You can decompress Drawing data with the command palette: 'Decompress current Excalidraw file'. For more info check in plugin settings under 'Saving'


# Excalidraw Data
## Text Elements
%%
## Drawing
```compressed-json
N4KAkARALgngDgUwgLgAQQQDwMYEMA2AlgCYBOuA7hADTgQBuCpAzoQPYB2KqATLZMzYBXUtiRoIACyhQ4zZAHoFAc0JRJQgEYA6bGwC2CgF7N6hbEcK4OCtptbErHALRY8RMpWdx8Q1TdIEfARcZgRmBShcZQUebQBWbQAGGjoghH0EDihmbgBtcDBQMBKIEm4IZwAFAA42ACUADQB9eoBmQn0AKUb6fQAZADkAEQBpQfrUkshYRArA7CiOZWCp

0sxuZx4kgEZtGpqko4AWA54anZ54/lKYTZ2auIBONuO298PLgDYn+LabyAUEjqbgPJ7aN7HJ5PADs8XiNXiLzhAKkCEIymkoLaiSeX2OPC+bSeOy+u3iXz4hUg1hW4lQSVRzCgpDYAGsEABhNj4NikCoAYh2CGFwrWkE0uGwbOUrKEHGI3N5/IkLOszDguEC2XFEAAZoR8PgAMqwVYSQQeXXM1kcgDqwMk3Cp0wgNvZCFNMHN6Et5VRcsxHHCuTQ

O1RbE12DUdzDR1RsuEcAAksRQ6g8gBdVF68iZVPcDhCI2owgKrAVXApAPCBXB5jp4qu2b0trUgC+TIQCGIoPixy+MNhOzeqMYLHYXDQSLHTFYnEGnDE2KSxyS7xhiNLzGG6SgPe4eoIYVRmlrxAAosFMtl00WS9SIEI4MRcPve2GYYT4jt3sc4T8qJEBwbKFsW+BAWw0oHmgR74GEhSdoUTaQOUEgAIIACoAJpGKMyZVP0jQAGpPMooxsE8kgIGw

xEAI7OLqLYVI4uD6JwvaohsaDOA8cRwnibzwgONQoo+saoLxX7aDsQ7xDCbRJEiSSPOuqJAsQIJhqcCRJNsI6kuSlLXI+1EYlicbHBCv6yTCUJ6a8bQ1KitI+oyj7uhySp8oKooikgp5SjKcoKt5KroGqHAalqWRQLqBpGl6Ppujy/oeSyHoOppTpoC6pSeZ6Zr0ilVo1n4kj1um4aPpGUoxqC8aPomz6pumWY5nmCAFmg94QY+ZbEBWEi4Dsuoh

cQlXcChMzwPSPAdl2MGoA8OzyV8pJXLOE6cKCslbfOHCLhwy5hrCbSXDsI7/P1O57ktcEno+Z7ype16xXe4Gos+r7vqCX5fD+7zxISPAwkBZagT1n2Pry0EfqgD0IIh4DZnQuBwHAppvvSTbQNRmQsVqoE3AwhAIBQABCQXNaFPI+RIAp6kzzNrBA2AiNqUDJvu+imraXJ0+FEBCv5Yok+zpCc9zGRU9KNOKoLFSRdFnOsxLUs8wAYoaJpFRUfqc

YUbMc7F0u8xl9qOs64sm9kZt8x6SXFQbau21zPP1MIQYhqCNuS6bPMAPJRvVcbuaU6sBxkmucFAmtsYaEkmRHbtmzH2TGoQRhzeHkCR3bPOYVgUDoUQyhTugwR6nFfsaxkWOkCXktsBQ1G4PDvW11H+gXgq6HN63ITwxAWqslQXcFxk/dj5hs3zOerPMNgrJGo03BQnsTmnPJtkKccxwk0vK/4Nh3DEnsm5PDwq0qZfSRfCTRhsAYU2PvQBBCPSO

yIRP7sZJ7L1JoSHGqzWUJBM7Z2dLnCAYDiCmgQHAbgydICwIALJsEGr3XAmhgjw0RiTWBYVX6ugpjyYepBlCSgABTXzBrwPa9C6FJASAASl1PUBAyhixanmJQ3ANDFLUF4II4RjIGSsIgD/I2+coAOw5MHKAk4PoPlKLmNiCAOHllIGWZQxDShZGwbg7gLJP6omwEQRBaATEIFRBwdRxjSCmJqkIKAwF6TWKkaUOwAArBAixmDGjsXAdBmC7E4Pu

seGxRspSKMYJhZ++A9EzTmBadIixJy6nZsyAws8UmoE7jDKCHI8GRKAqEEu6S4kJLAkaZGYAkKQASuEKa7YQDtiAA===
```
%%

EXCALIDRAW------

and here is an example of a note embedding the drawing

-----TEST NOTE

---
tags: this_is_a_test_note uncategorized
icon: TiArrowsRandom
aliases:
  - Uncategorized This is a test note
created: 2024-09-16
modified: 2024-09-16T21:04:13+02:00
---
Test note 123

![[Drawing 2024-09-16 21.02.24.excalidraw]]

TEST NOTE------


Example of how it is rendered in live-preview (default editing mode in Obsidian)

<img width="881" alt="image" src="https://github.com/user-attachments/assets/6065031c-202b-423b-bb06-432f8a582bbe">


Interestingly it looks fine in reading-mode

<img width="653" alt="image" src="https://github.com/user-attachments/assets/96409774-eb43-4e7d-bc65-a02032aee3f2">

**Comment by acrylicus** [comment]
Just checking in on this to see if there has been any workaround found?

**Comment by mProjectsCode** [comment]
just released a new version that should fix this.

**Comment by acrylicus** [comment]
Works - great stuff @mProjectsCode

**Comment by S4njer** [comment]
Thanks a lot, the plugins is working now!
