### ISSUE TITLE
[Feature Request] add syntax highlighting for the Odin langage

### ISSUE THREAD

**Issue by LaurentOngaro** [mProjectsCode/obsidian-shiki-plugin#23]
Please add syntax highlighting for the [Odin langage] (https://odin-lang.org)

A quick work around could be to reference "odin" as an alias for "go" because the syntaxes are similar.
I've tried to do it by myself but I failed to understand where I could make this change in the code, mainly because to main file has been minified, so it s very difficult to read and modify.

**Comment by mProjectsCode** [comment]
The plugin will only ship with the languages included in shiki, though there is a FR #21 to import custom languages.

**Comment by mProjectsCode** [comment]
> [...] mainly because to main file has been minified, so it s very difficult to read and modify.

You should look at the source code and not the transpiled and minified code that is included in a release. 😉

**Comment by LaurentOngaro** [comment]
I've done it, but it did not managed to build the plugin from source due to dependency errors. 
So I have to check the compiled file (not easy) and I've failed.

I've done:
```
git clone ...
git pull
npm -i
npm run build 
```
and it failed 

Do you have some tips to build it ?

**Comment by mProjectsCode** [comment]
you should use `bun` and not `npm`

**Comment by LaurentOngaro** [comment]
I've managed to build main.js using bun, using the following commands:
```
npm install bun -g
bun install
bun run build
```
Then I replaced the new built files in the folder of the plugin within my obsidian vault ... and TADA ! it works !

Odin code is displayed with syntax highlight

Thanks for all !

**Comment by LaurentOngaro** [comment]
I've noticed a small issue.

It seems that the string in the code bloc for Odin is case sensitive !

if the code bloc start with  ```Odin

It is highlighted as expected, 

but not if it starts with ```odin

You can see it in the following Gif 

![pb_odin](https://github.com/user-attachments/assets/458a0f00-5822-4749-91ac-a67386e58bc8)

For info, the version with the lower case O is the more usual in Odin code blocs.

I've tested and that's not the case with Go for instance. Both versions "Go" and "go" are working well.

**Comment by mProjectsCode** [comment]
That seems to be caused by the Odin grammar file having `Odin` set as the name and not something lowercase.

**Comment by LaurentOngaro** [comment]
You were right ! 
Changing `"name": "Odin"` by `"name": "odin"` in the `odin.json` file switches the case sensitivity of the odin code blocks.
It solved my issue. Thanks
