### ISSUE TITLE
I added PineScript support

### ISSUE THREAD

**Issue by Fred-Vatin** [mProjectsCode/obsidian-shiki-plugin#25]
Hi,

Thanks a lot for this plugin. Now I can add missing languages.

Here is how I added PineScript support:
- Download [pine.tmLanguage.json](https://github.com/frizLabz-FFriZz/Pine-Script-v5-VS-Code/blob/main/themes/pine.tmLanguage.json) from the great VS Code extension.
- Open the file and change the name to `pine` instead of `Pine Script`
- Put it on a folder inside your vault and reference it in shiki settings, for instance `/MyScripts/Shiki/Languages/`
- Follow the readme about how to add custom language.
- Restart Obsidian

You’ll need an enhanced theme to highlight some keywords. You can find one in the same [repo](https://github.com/frizLabz-FFriZz/Pine-Script-v5-VS-Code/tree/main/themes) as above. Or in my VS Code theme [here](https://github.com/Fred-Vatin/never-be-lost/tree/master/themes). If importing those files doesn’t work directly, install the needed themes in VS Code then run this command from palette: `Generate color theme from current settings`. A new file is open in VS Code with the theme. Search for comments and delete them then save the file as `.json` and NOT `.jsonc`. It worked for me.

I wonder if this language can be integrated in the plugin so every user can has it by default.

**Comment by mProjectsCode** [comment]
> I wonder if this language can be integrated in the plugin so every user can has it by default.

No. The plugin will only ship with languages that ship with shiki. The plugin is sadly already very big.

**Comment by Fred-Vatin** [comment]
I made a request to their TextMate repo: https://github.com/shikijs/textmate-grammars-themes/issues/97
