### ISSUE TITLE
Can't enable on android obsidian: Failed To Load Error

### ISSUE THREAD

**Issue by wychwitch** [mProjectsCode/obsidian-shiki-plugin#3]
-   [x] The Plugin is up to date
-   [x] Obsidian is up to date (I'm fairly certain)

**Describe the bug**
After installing the plugin, when I try to enable it I get a "failed to load plugin" error. I haven't tried on my computer, but I assume it should be fine there.

**To Reproduce**
1. install the plugin.
2. Try to enable it.

**Expected behavior**
The plugin to be enabled!

**Screenshots**
![Screenshot_20240401_110128_Obsidian](https://github.com/mProjectsCode/obsidian-shiki-plugin/assets/1291820/4f72cb56-9beb-4c5f-9abb-cb60dfd6ae37)

this is my android obsidian version
![Screenshot_20240401_110142_Obsidian](https://github.com/mProjectsCode/obsidian-shiki-plugin/assets/1291820/45f31246-aae9-4ffc-bd50-146a11f56c20)

**Occurs on**

-   [ ] Windows
-   [ ] macOS
-   [ ] Linux
-   [x] Android
-   [ ] iOS

**Plugin version**
0.2.3

Thanks in advance! I hope I'm not overlooking something obvious.

**Comment by mProjectsCode** [comment]
I can reproduce this. It seems like EC is depending on `postcss` which expects a node js environment.

**Comment by mProjectsCode** [comment]
I think I successfully polyfilled the used node APIs in `0.2.4`.
