### ISSUE TITLE
HighLight line with "[]"  make error

### ISSUE THREAD

**Issue by Tback1** [mProjectsCode/obsidian-shiki-plugin#32]
-   [x] The Plugin is up to date
-   [x] Obsidian is up to date

**To Reproduce**

`javascript showLineNumbers {hl_lines=[22,23,24]} {26,27,28,32-34} {[35,36,37]}`

`javascript showLineNumbers {hl_lines=[22,23,24,25]} {26,27,28,32-34} {[35,36,37,38]}`

**Screenshots**
![image](https://github.com/user-attachments/assets/ace270c6-a698-4d47-85d9-9b66993b594a)

**Occurs on**

-   [x] Windows
-   [ ] macOS
-   [ ] Linux
-   [ ] Android
-   [ ] iOS

**Plugin version**
0.44

**Additional context**

The array formed by '[]' is incorrectly recognized as linenumber, and this problem is found because of the previous [Hugo](https://github.com/aarol/obsidian-hugo-codeblock-highlight) extension of the plug-in form {hl_lines=[22,23,24]}, when I manually corrected it, I found that the middle 23 lines can still be highlighted, after experimentsIn fact, it is found that the whole array is removed from the head and tail, and the line markers in the middle can be used.For example, {[35,36,37,38]} would remove 35 and 38 instead of 36 and 37

Is this a bug with lax validation in array form?

**Comment by mProjectsCode** [comment]
Square brackets like that are not supported. See [here](https://expressive-code.com/key-features/text-markers/) for a more extensive list of what is supported and what is not.

**Comment by Tback1** [comment]
> Square brackets like that are not supported. See [here](https://expressive-code.com/key-features/text-markers/) for a more extensive list of what is supported and what is not.

I think the [] will not allowed in the config, not even the part of it.
