### ISSUE TITLE
Language is missing

### ISSUE THREAD

**Issue by EscobarPablo** [mProjectsCode/obsidian-shiki-plugin#37]
Hello! The site https://shiki.style/languages ​​says that the languages ​​"bsl" and "sdbl" are supported. But they are not available in the obsidian plugin. Is it possible to add these languages ​​to the plugin?

**Comment by ArtemB91** [comment]
same problem

**Comment by nixel2007** [comment]
You just need to bump [this dependency](https://github.com/mProjectsCode/obsidian-shiki-plugin/blob/master/package.json#L54), I guess.

**Comment by mProjectsCode** [comment]
just updated shiki and EC to the latest versions.

**Comment by nixel2007** [comment]
![image](https://github.com/user-attachments/assets/dce5f820-b979-4211-ab6f-a004fbc96126)

Can confirm, it works, thanks!

**Comment by EscobarPablo** [comment]
> ![image](https://private-user-images.githubusercontent.com/1132840/392371663-dce5f820-b979-4211-ab6f-a004fbc96126.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzMzMTUwNzEsIm5iZiI6MTczMzMxNDc3MSwicGF0aCI6Ii8xMTMyODQwLzM5MjM3MTY2My1kY2U1ZjgyMC1iOTc5LTQyMTEtYWI2Zi1hMDA0ZmJjOTYxMjYucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MTIwNCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDEyMDRUMTIxOTMxWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9N2QxOWM4ZjAyMjA4YTM1YmJmNDg2OGZhMTAyN2IwZjE4ZTExOGM4ZWU1M2VlMjJiODczZWEwZDMxOTIxODhhZCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QifQ.03UZ0y5Sf-wbB84Fne6gbqBcX5Ff2szC8giVGsEwrgU)
> 
> Can confirm, it works, thanks!

Никита, если я правильно понял, то это Вы автор добавления bsl и sdbl в shiki. 
![Screenshot 2024-12-04 151920](https://github.com/user-attachments/assets/f9bd8b7e-21b9-491b-b447-5c55781a28c4)
На изображении при создании переменная Массив1 имеет один цвет, а а далее при обращении к методам расцветка уже не применяется. И так со всеми объектами. Это нельзя никак исправить?

**Comment by EscobarPablo** [comment]
> just updated shiki and EC to the latest versions.

Thank you very much! It worked!

**Comment by nixel2007** [comment]
> На изображении при создании переменная Массив1 имеет один цвет, а а далее при обращении к методам расцветка уже не применяется. И так со всеми объектами. Это нельзя никак исправить?

those are highlighting rules defined in grammar. The assignment to the variable is highlighted additionally. It works the same in vscode, github and shiki, see snippet below:

```bsl
Массив = Новый Массив;
Массив.Добавить("1");
```

but lets continue the discussion (if needed) in my telegram channel or in @bsl_language_server telegram chat.

this issue can be closed. thanks again.

**Comment by mProjectsCode** [comment]
Can we please keep the discussions on this repo in English?

**Comment by nixel2007** [comment]
>  Can we please keep the discussions on this repo in English?

hey, @mProjectsCode, sorry for that. sure, that's why I answered in English. We will continue the discussion in some other place. Thanks for your work!
