### ISSUE TITLE
[FR] Theming Shiki codeblock ?

### ISSUE THREAD

**Issue by I-Pch** [mProjectsCode/obsidian-shiki-plugin#4]
**Is your feature request related to a problem? Please describe.**
Nope, it's absolutely not related to any issue 😄 ! 

It's just that, while going through [Expressive Code](https://expressive-code.com/) documentation, I discovered that, apparently, Expressive Code can be implemented with [bundled themes](https://expressive-code.com/guides/themes/#using-bundled-themes) 😊 (Shiki also seems to have a similar [feature](https://shiki.style/guide/bundles)) ... 

So, of course, I tried to add/change the theme applied "by default" to my shiki codeblock but it didn't work as mProjectsCode created a dedicated and very nice Obsidian theme 😄 !

Not an issue though, as one can try and look at the `styles.css` file of the plugin and potentially modify it 😊 !

But I still think it would be nice to be able to change the theme, if one wishes 😊 ...

---
**Describe the solution you'd like**
I think there would be 3 possibilities : 

1. A global setting to select the theme that should be applied when the shiki codeblock is rendered 
2. A "configuration" to add to any shiki codeblock (like `wrap` and/or `showLineNumbers` codeblock configurations available) to bypass the default "Shiki Obsidian theme" 
3. A mix of both option 1 & 2 😊 

(I have honestly no preference... I mean, I have no idea if any of this would be feasible or the added work/maintenance it could represent 😇 )

---
**Additional context**
Thank you so very much once again mProjectsCode 🙌 !

Shiki Highlighter is absolutely wonderful 💜 ! 
It's flexible, adds really nice features to codeblocks while also being more than easy to use 🥳 !!!

**Comment by mProjectsCode** [comment]
Implemented as a global setting in `0.3.0`

**Comment by I-Pch** [comment]
I know you know how happy and grateful I am to see this feature being implemented 🥳 , so I'm just going to say, once more: Thank you 😁 💜 !!!
