### ISSUE TITLE
First processed codeblock result is hidden on reading mode

### ISSUE THREAD

**Issue by Krakor92** [mProjectsCode/obsidian-shiki-plugin#6]
-   [x] The Plugin is up to date (0.3.1)
-   [x] Obsidian and Installer are up to date (1.5.12)

**Describe the bug**

When a processed codeblock (dataviewjs, js-engine, ...) sits right at the top of a file with no character above it (except newlines), it won't get rendered on reading mode even though the DOM gets populated by whatever the codeblock produces

**To Reproduce**

1. Open the Sandbox vault
2. Install `Shiki Highlighter` and any other plugin that register a `MarkdownPostProcessor` (`JS Engine` for example)
3. Create a new empty file and paste a simple codeblock that render something
~~~
```js-engine
return 1
```
~~~
4. Switch to reading mode

**Expected behavior**
You can see a `1`

**Actual behavior**
Nothing is visible

**Tested on**

-   [x] Linux
-   [x] Android
-   [x] iPadOS

**Additional context**
- Placing a pair of %% with a character inside, or any other character above the code block, will make it behave as expected.
- It looks like the culprit code is [here](https://github.com/mProjectsCode/obsidian-shiki-plugin/blob/master/styles.css#L80-L83). The rule should be more specific

**Comment by mProjectsCode** [comment]
thanks, should be fixed in `0.3.2`
