### ISSUE TITLE
Dev Tools Console: SharedArrayBuffers (SABs) are deprecated

### ISSUE THREAD

**Issue by visua1hue** [mProjectsCode/obsidian-shiki-plugin#8]
-   [x] The Plugin is up-to-date
-   [x] Obsidian is up-to-date

**Describe the bug**
Obsidian dev tools console shows an issue with a deprecated feature.

> SharedArrayBuffer will require cross-origin isolation. See [https://developer.chrome.com/blog/enabling-shared-array-buffer/](https://developer.chrome.com/blog/enabling-shared-array-buffer/) for more details. plugin:shiki-highlighter:13891

**To Reproduce**

1. Open Dev Tools
2. Click on 'Issues'

**Screenshots**

![Screenshot 2024-04-23 191502](https://github.com/mProjectsCode/obsidian-shiki-plugin/assets/54352478/638b6268-f012-4297-bfa3-ca2fd00c4180)

**Occurs on**

-   [x] Windows
-   [x] macOS
-   [ ] Linux
-   [ ] Android
-   [ ] iOS

**Plugin version**
0.3.2

**Additional context**
n/a

**Comment by mProjectsCode** [comment]
This is in polyfill code, so nothing to worry about.
